### PR TITLE
Updating notebook for april 2022 release

### PR DESCRIPTION
**Pull request by IAlibay**
~ don't merge yet ~

### CODE REVIEW

**Comment by IAlibay** [comment]
Workflow diagram needs updating but let's get the notebook out first, can update diagram tomorrow.

**Review by richardjgowers — CHANGES_REQUESTED** [review]
You've got a typo, in `'HBonds'` you're spelling it `'Hbonds'`.  Tbh we should normalize this internally to avoid this sort of finger trouble, but it'll need to get fixed here for now.

I wonder if this would be better if we split out the JNK ligand set into a separate notebook (to showcase the network creation system) and mostly skip over it here.

**Review by richardjgowers — APPROVED** [review]

**Comment by richardjgowers** [comment]
@mikemhenry I think I'm gonna have to cut a 0.2.1 since we found a couple little issues, then I'll pin this repo to that ( so we can develop freely)

**Comment by mikemhenry** [comment]
> @mikemhenry I think I'm gonna have to cut a 0.2.1 since we found a couple little issues, then I'll pin this repo to that ( so we can develop freely)

Sounds good! I asked Irfan this but I might as well make this public:

I  need to make the simulations shorter so the CI can do them, do you have any objects to me adding some sort of comment that says "you will want to run these longer for production but for demonstration purposes we are going to do only a few steps" or something like that?

The alternative is to use tags to skip the cells (users won't see them) but if we skip them 1) they won't be tested and 2) the analysis cells will also have to be skipped.

**Comment by IAlibay** [comment]
The comment re: longer simulations should be in the notebook for this month.

**Comment by IAlibay** [comment]
I would prefer we just skip the cells from CI though, it's not necessary, at that point we should know the things work.

**Comment by mikemhenry** [comment]
Fixes #3

**Pull request merged**
