### PR TITLE
Add support for Google Colab

### PR DESCRIPTION
**Pull request by mikemhenry**
* [ ] Need to update links to point to `main` instead of PR branch

Note: I made a special installer that has extra deps for the notebook and attached it to a release on this repo.

### CODE REVIEW

**Comment by mikemhenry** [comment]
Grumble `OSError: File error: Bad input file inputs/ligands.sdf` I forgot that google colab does things differently. This _should_ work if we ship that sdf. We could also clone the repo in one of the steps, but then we have to modify the file path...

**Comment by IAlibay** [comment]
> Grumble `OSError: File error: Bad input file inputs/ligands.sdf` I forgot that google colab does things differently. This _should_ work if we ship that sdf. We could also clone the repo in one of the steps, but then we have to modify the file path...

This is probably why we should be packaging up those files. Then we could just pip install the repo and access the data files directly.

**Comment by mikemhenry** [comment]
I think using our new openfe fetch tool could be a solution for the files we don't want to ship

**Comment by mikemhenry** [comment]
Now that the fetch tool is working, this should be much easier!

**Comment by mikemhenry** [comment]
Going to redo this in a different PR

**Comment by mikemhenry** [comment]
Superseded by https://github.com/OpenFreeEnergy/ExampleNotebooks/pull/69

**Pull request closed without merging**
