### PR TITLE
CLI tutorial (markdown)

### PR DESCRIPTION
**Pull request by dwhswenson**
This adds a basic CLI tutorial. The goal is to walk the user through the process of setting up, running, and gathering results using the CLI.

Audience is people for whom this is their first experience with OpenFE, and they're not super into Python. They already know the science, however, and may know some of the tools in this space (LOMAP, etc).

### CODE REVIEW

**Comment by richardjgowers** [comment]
@dwhswenson can this get formatted into a notebook?  Currently within binder the markdown isn't rendered.

**Comment by dwhswenson** [comment]
ufff, I guess? Do you want the commands to all be runnable then? I was kind of trying to avoid that, because running a ton of simulations (or calling sbatch where it doesn't exist) kinda sucks.

**Comment by dwhswenson** [comment]
@richardjgowers : Try again.

**Comment by richardjgowers** [comment]
@dwhswenson yeah ok this is better

**Review by richardjgowers — APPROVED** [review]

**Pull request merged**
