### PR TITLE
Added tutorial for building AlchemicalNetworks

### PR DESCRIPTION
**Pull request by dotsdl**
This was originally created for [`alchemiscale`](https://github.com/openforcefield/alchemiscale/pull/46), but is being contributed here instead, since it really is a `gufe` tutorial.

### CODE REVIEW

**Comment by dotsdl** [comment]
This notebook will require `openfe-benchmarks` be added to the Binder environment to run.

**Comment by dotsdl** [comment]
Also need `perses`, in particular content from this branch: https://github.com/choderalab/perses/pull/1066

`perses` will require `numba` as well.

**Comment by dotsdl** [comment]
For reference, we used the following environment file for building the `conda` env used to run this notebook:

```yaml
name: fah-alchemy-client
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
  - openeye
dependencies:
  - python =3.9

  # gufe dependencies
  - numpy
  - networkx
  - rdkit
  - pip
  - pydantic
  - openff-toolkit
  - openff-units
  - typing-extensions

  # perses dependencies
  - tqdm
  - openmm
  
  ## cli
  - click

  # needed for openfe
  - lomap2>=2.1.0
   
  ## needed for perses
  - openmmtools
  - openmmforcefields
  - openmoltools
  - cloudpathlib
  - dask
  - distributed
  - openeye-toolkits

  - pip:
    - git+https://github.com/OpenFreeEnergy/gufe
    - git+https://github.com/OpenFreeEnergy/openfe
    - git+https://github.com/OpenFreeEnergy/openfe-benchmarks
    - git+https://github.com/mikemhenry/openff-models.git@support_nested_models
    - git+https://github.com/choderalab/perses@protocol-neqcyc

```

**Comment by richardjgowers** [comment]
thanks @dotsdl .  I can fix this up and take it from here

**Comment by dotsdl** [comment]
Thanks @richardjgowers! I've pushed my latest updates; I'll pass it off to you from here.

I noticed that our `Settings` object appears to be unhashable, which chokes up creation of `AlchemicalNetwork`s from a list of `Transformation`s, each with a `Settings` object. You can see this in cell `[24]` in the notebook.

**Comment by dotsdl** [comment]
Might consider using the `openfe` REPEX protocol as the example instead to avoid OpenEye requirement for `perses`.

**Comment by dotsdl** [comment]
We need to use pre-baked mappings in this notebook; currently not using any.

**Comment by dotsdl** [comment]
@richardjgowers do we have a way to add some pre-baked mappings to this choice of network? That's the only blocker (I think) to this being a functional example notebook, and I'm itching to use it for ad-hoc testing in `alchemiscale`.

**Comment by dotsdl** [comment]
We can also switch over to the RepEx protocol in `openfe` as our example protocol.

**Comment by richardjgowers** [comment]
supersedes #42

**Pull request closed without merging**
