### PR TITLE
Fix old showcase for 1.0 release

### PR DESCRIPTION
**Pull request by hannahbaumann**

### CODE REVIEW

**Comment by hannahbaumann** [comment]
This PR just fixes the notebook to work with openfe 1.0 (settings, mapping), otherwise this is still the same old notebook. This is to be replaced by the new notebook soon.

**Comment by hannahbaumann** [comment]
The two notebooks that are failing here have been fixed in PR https://github.com/OpenFreeEnergy/ExampleNotebooks/pull/99

**Comment by mikemhenry** [comment]
If I understand this PR correctly @richardjgowers @hannahbaumann the point is to just get the notebook we are using for http://try.openfree.energy/ to work with openfe 1.0

**Comment by mikemhenry** [comment]
colab link here:
https://colab.research.google.com/github/OpenFreeEnergy/ExampleNotebooks/blob/fix_showcase/openmm_rbfe/OpenFE_showcase_1_RBFE_of_T4lysozyme.ipynb

**Comment by mikemhenry** [comment]
image
looks like it can grab a GPU! 

Have to make a few changes still, will ping for reviews when ready

**Comment by mikemhenry** [comment]
@richardjgowers This is ready to merge!

**Review by mikemhenry — APPROVED** [review]

**Comment by mikemhenry** [comment]
Also thanks Hannah for fixing the API changes!

**Comment by mikemhenry** [comment]
we had 2 notebooks still failing on CI as @hannahbaumann noted, I pulled in changes from #99 by hand to fix those two notebooks, assuming CI passes (at least on linux), I will get this merged in!

**Pull request merged**
